
version: '3'

services:

  dev:

    command: ash

    env_file: .env

    image: node:alpine

    ports:
    - 3000:3000

    working_dir: /app

    volumes:
      - /Users/rsdavis/Desktop/kitethere/client:/app